version: '3.6'

services:
  consumer_kycerrors:
    image: jhovanylinkin/rabbitmq-rocketchat-publisher:latest
    restart: unless-stopped
    container_name: rabbitmq-rocketchat
    volumes:
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
